# Generated by Django 3.0.6 on 2021-04-30 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='nickname',
            field=models.TextField(blank=True, null=True),
        ),
    ]
