# Generated by Django 3.0.6 on 2021-04-16 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='integer',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
