# Generated by Django 3.0.6 on 2021-04-16 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_backend', '0002_post_integer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='integer',
        ),
    ]
