# Generated by Django 3.0.6 on 2021-04-21 05:58

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('core_backend', '0003_remove_post_integer'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+17759902822', max_length=128, region=None),
            preserve_default=False,
        ),
    ]
